---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: "user-manager"
    access: "true"
    group: local
  name: user-manager
  namespace: hosting
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: "user-manager"
      access: "true"
      group: local
  template:
    metadata:
      labels:
        app: "user-manager"
        access: "true"
        group: local
    spec:
      containers:
      - image: ${IMAGE}
        name: user-manager
        env:
        - name: GIN_MODE
          value: '${GIN_MODE}'
        - name: CH_USER_LOG_LEVEL
          value: '${CH_USER_LOG_LEVEL}'
        - name: CH_USER_PG_LOGIN
          value: '${CH_USER_PG_LOGIN}'
        - name: CH_USER_PG_PASSWORD
          value: '${CH_USER_PG_PASSWORD}'
        - name: CH_USER_PG_ADDR
          value: '${CH_USER_PG_ADDR}'
        - name: CH_USER_PG_DBNAME
          value: '${CH_USER_PG_DBNAME}'
        - name: CH_USER_PG_NOSSL
          value: '${CH_USER_PG_NOSSL}'
        - name: CH_USER_MAIL_URL
          value: '${CH_USER_MAIL_URL}'
        - name: CH_USER_RECAPTCHA_KEY
          value: '${CH_USER_RECAPTCHA_KEY}'
        - name: CH_USER_RECAPTCHA
          value: '${CH_USER_RECAPTCHA}'
        - name: CH_USER_GITHUB_APP_ID
          value: '${CH_USER_GITHUB_APP_ID}'
        - name: CH_USER_GITHUB_SECRET
          value: '${CH_USER_GITHUB_SECRET}'
        - name: CH_USER_GOOGLE_APP_ID
          value: '${CH_USER_GOOGLE_APP_ID}'
        - name: CH_USER_GOOGLE_SECRET
          value: '${CH_USER_GOOGLE_SECRET}'
        - name: CH_USER_FACEBOOK_APP_ID
          value: '${CH_USER_FACEBOOK_APP_ID}'
        - name: CH_USER_FACEBOOK_SECRET
          value: '${CH_USER_FACEBOOK_SECRET}'
        - name: CH_USER_AUTH_GRPC_ADDR
          value: '${CH_USER_AUTH_GRPC_ADDR}'
        - name: CH_USER_LISTEN_ADDR
          value: '${CH_USER_LISTEN_ADDR}'
        - name: CH_USER_WEB_API_URL
          value: '${CH_USER_WEB_API_URL}'
      imagePullSecrets:
      - name: gitlab-registry
