required = ["git.containerum.net/ch/auth"]

[prune]
    non-go = true
    go-tests = true
    unused-packages = true

  [[prune.project]]
    name = "git.containerum.net/ch/auth"
    non-go = false

  [[prune.project]]
    name = "github.com/containerum/utils"
    non-go = false

  [[prune.project]]
    name = "github.com/containerum/cherry"
    non-go = false

[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/auth"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattes/migrate"
  version = "3.0.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.8.2"

[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/uuid"

[[constraint]]
  name = "github.com/containerum/cherry"
  version = "1.0.1-rc2"

[[constraint]]
  name = "github.com/containerum/utils"
  version = "1.0.0"
