{{- if or .Values.env.local.PG_PASSWORD .Values.env.local.ADMIN_PASSWORD }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.env.local.PG_PASSWORD }}
  pg-password: {{ .Values.env.local.PG_PASSWORD | b64enc }}
  {{- end }}
  {{- if .Values.env.local.ADMIN_PASSWORD }}
  admin-password: {{ .Values.env.local.ADMIN_PASSWORD | b64enc }}
  {{- end }}
{{- end }}
