tags:
  db: true
  platformdb: false

replicaCount: 1

image:
  repository: containerum/user
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret:

service:
  port: 8111
  targetPort: 8111
  externalIP:

env:
  global:
    GIN_MODE: debug
    DEBUG: true
    PORT: ":8111"
    PG_LOGIN: "usermanager"
    PG_DBNAME: "usermanager"
    PG_NOSSL: true
    MIGRATIONS_PATH: "migrations"
    MAIL: "http"
    RECAPTCHA: "dummy"
    RECAPTCHA_KEY: "recaptcha_key"
    OAUTH_CLIENTS: "http"
    PERMISSIONS: "http"
    USER_MANAGER: "impl"
  local:
    PG_PASSWORD:
    PG_ADDR: "postgres-master.postgres.svc.cluster.local:5432"
    PERMISSIONS_URL: "http://permissions:4242"
    AUTH_URL: "http://auth:1111"
    MAIL_URL: "mail-templater:7070"
    ADMIN_PASSWORD:

postgresql:
  persistence:
    enabled: false
  postgresDatabase: usermanager
  # postgresUser: postgres
  # postgresPassword: password
