tags:
  db: true
  platformdb: false

replicaCount: 1

image:
  repository: containerum/user
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret:

service:
  port: 8111
  targetPort: 8111
  externalIP:

env:
  global:
    GIN_MODE: debug
    CH_USER_DEBUG: true
    CH_USER_TEXTLOG: true
    CH_USER_LISTEN_ADDR: ":8111"
    CH_USER_PG_LOGIN: "usermanager"
    CH_USER_PG_DBNAME: "usermanager"
    CH_USER_PG_NOSSL: true
    CH_USER_MIGRATIONS_PATH: "migrations"
    CH_USER_MAIL: "http"
    CH_USER_RECAPTCHA: "dummy"
    CH_USER_RECAPTCHA_KEY: "recaptcha_key"
    CH_USER_OAUTH_CLIENTS: "http"
    CH_USER_PERMISSIONS: "http"
    CH_USER_USER_MANAGER: "impl"
  local:
    CH_USER_PG_PASSWORD:
    CH_USER_PG_ADDR: "postgres-master.postgres.svc.cluster.local:5432"
<<<<<<< HEAD
    CH_USER_RESOURCE_SERVICE_URL: "http://permissions:4242"
    CH_USER_AUTH_GRPC_ADDR: "auth:1112"
=======
    CH_USER_PERMISSIONS_URL: "http:///permissions:4242"
    CH_USER_AUTH_GRPC_ADDR: "ch-auth:1112"
>>>>>>> a68f79e3942ebcbc7ffa6e6199545b86d1236497
    CH_USER_MAIL_URL: "mail-templater:7070"

postgresql:
  persistence:
    enabled: false
  postgresDatabase: usermanager
  # postgresUser: postgres
  # postgresPassword: password
